version: "2.1"

services:
    node-red:
        build:
            context: ./node-red
        restart: unless-stopped
        # depends_on:
        #     mongodb:
        #         condition: service_healthy
        #     mqtt:
        #         condition: service_healthy
        environment:
            - ADMIN_USERNAME=${ADMIN_USERNAME}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - USER_USERNAME=${USER_USERNAME}
            - USER_PASSWORD=${USER_PASSWORD}
        ports:
            - "1880:1880"
            - "1883:1883"
        volumes:
            - ./node-red/flows:/data/lib/flows:z
            - ./node-red/settings.js:/data/settings.js
            - node-data:/data

    # mongodb:
    #     build:
    #         context: ./mongodb
    #     environment:
    #       - MONGO_DATA_DIR=/data/db
    #       - MONGO_LOG_DIR=/dev/null
    #       # - MONGODB_USER="user"
    #       # - MONGODB_PASS="pass"
    #     volumes:
    #       - ./data/db:/data/db
    #     ports:
    #         - 27017:27017
    #     # command: mongod --smallfiles --logpath=/dev/null # --quiet

    # mqtt:
    #     build:
    #         context: ./mqtt
    #     ports:
    #         - "1883:1883"
    #         - "9001:9001"
    #     # restart: unless-stopped
    #     # volumes:
    #     #     - ./mqtt/config:/mosquitto/config
    #     #     - ./mqtt/log:/mosquitto/log
    #     #     - mqtt-data:/mosquitto/data
    #     # environment:
    #     #     USERNAME: 'prueba'
    #     #     PASSWORD: 'prueba'
    #     #     SYS: '__healthcheck'
    #     healthcheck:
    #         test: mosquitto_pub -t '__healthcheck/' -m 1
    #         interval: 5s
    #         timeout: 10s
    #         retries: 7

volumes:
    node-data:
