FROM nodered/node-red-docker:rpi
# FROM nodered/node-red-docker

RUN npm install node-red-contrib-owfs
RUN npm install node-red-contrib-mqtt-broker
RUN npm install node-red-dashboard
RUN npm install node-red-contrib-ds18b20-sensor